import { BET_LOCK_TIME_SECONDS, GAME_TIME_SECONDS } from "@color-trading/shared";

import { env } from "../../config/env.js";

export const ROUND_DURATION_SECONDS = env.GAME_ROUND_DURATION_SECONDS ?? GAME_TIME_SECONDS;
export const BET_LOCK_AFTER_SECONDS = env.GAME_BETTING_DURATION_SECONDS ?? BET_LOCK_TIME_SECONDS;
export const ROUND_DURATION_MS = ROUND_DURATION_SECONDS * 1000;
export const BET_LOCK_AFTER_MS = BET_LOCK_AFTER_SECONDS * 1000;
export const ROUND_LOCK_TTL_MS = env.GAME_ROUND_LOCK_TTL_MS;
export const ROUND_SCHEDULER_TICK_MS = env.GAME_SCHEDULER_TICK_MS;
export const WIN_PAYOUT_MULTIPLIER = 2;
export const WINNER_SETTLEMENT_CONCURRENCY = 100;
export const MAX_BET_PER_USER_PER_ROUND = BigInt(env.GAME_MAX_BET_PER_USER_PER_ROUND);
export const MAX_EXPOSURE_PER_COLOR = BigInt(env.GAME_MAX_EXPOSURE_PER_COLOR);

export const ROUND_ENGINE_CONFIG = {
  lifecycle: ["WAITING", "BETTING", "LOCKED", "RESULT", "SETTLED"],
  roundDurationSeconds: ROUND_DURATION_SECONDS,
  bettingDurationSeconds: BET_LOCK_AFTER_SECONDS,
  lockedDurationSeconds: ROUND_DURATION_SECONDS - BET_LOCK_AFTER_SECONDS,
  schedulerTickMs: ROUND_SCHEDULER_TICK_MS,
  redisLockTtlMs: ROUND_LOCK_TTL_MS,
  maxBetPerUserPerRound: env.GAME_MAX_BET_PER_USER_PER_ROUND,
  maxExposurePerColor: env.GAME_MAX_EXPOSURE_PER_COLOR,
} as const;
